#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🌐 Running e2e tests before push..."
pnpm test:e2e
E2E_EXIT_CODE=$?

if [ $E2E_EXIT_CODE -ne 0 ]; then
  echo "❌ E2E tests failed. Push aborted."
  exit $E2E_EXIT_CODE
fi
