name: Deploy Landing App

on:
  push:
    branches: [main]
    paths:
      - 'apps/landing/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
      - '.github/workflows/deploy-landing.yml'
  # Allow manual triggering
  workflow_dispatch:

# Cancel in-progress runs on new pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-landing:
    name: Deploy Landing App
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      app-name: landing
      project-id-secret: VERCEL_PROJECT_ID_LANDING
      sentry-project-secret: SENTRY_PROJECT_LANDING
      working-directory: ./apps/landing
      filter-paths: |
        apps/landing/**
        packages/**
        package.json
        pnpm-lock.yaml
        turbo.json
        .github/workflows/deploy-landing.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
